// Generated by gencpp from file auto_control/MsgCommand.msg
// DO NOT EDIT!


#ifndef AUTO_CONTROL_MESSAGE_MSGCOMMAND_H
#define AUTO_CONTROL_MESSAGE_MSGCOMMAND_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace auto_control
{
template <class ContainerAllocator>
struct MsgCommand_
{
  typedef MsgCommand_<ContainerAllocator> Type;

  MsgCommand_()
    : command(0.0)  {
    }
  MsgCommand_(const ContainerAllocator& _alloc)
    : command(0.0)  {
  (void)_alloc;
    }



   typedef float _command_type;
  _command_type command;





  typedef boost::shared_ptr< ::auto_control::MsgCommand_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::auto_control::MsgCommand_<ContainerAllocator> const> ConstPtr;

}; // struct MsgCommand_

typedef ::auto_control::MsgCommand_<std::allocator<void> > MsgCommand;

typedef boost::shared_ptr< ::auto_control::MsgCommand > MsgCommandPtr;
typedef boost::shared_ptr< ::auto_control::MsgCommand const> MsgCommandConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::auto_control::MsgCommand_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::auto_control::MsgCommand_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::auto_control::MsgCommand_<ContainerAllocator1> & lhs, const ::auto_control::MsgCommand_<ContainerAllocator2> & rhs)
{
  return lhs.command == rhs.command;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::auto_control::MsgCommand_<ContainerAllocator1> & lhs, const ::auto_control::MsgCommand_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace auto_control

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::auto_control::MsgCommand_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::auto_control::MsgCommand_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::auto_control::MsgCommand_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::auto_control::MsgCommand_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::auto_control::MsgCommand_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::auto_control::MsgCommand_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::auto_control::MsgCommand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "7a381543013b116822c4c5bfba61dfce";
  }

  static const char* value(const ::auto_control::MsgCommand_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x7a381543013b1168ULL;
  static const uint64_t static_value2 = 0x22c4c5bfba61dfceULL;
};

template<class ContainerAllocator>
struct DataType< ::auto_control::MsgCommand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "auto_control/MsgCommand";
  }

  static const char* value(const ::auto_control::MsgCommand_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::auto_control::MsgCommand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 command\n"
;
  }

  static const char* value(const ::auto_control::MsgCommand_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::auto_control::MsgCommand_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.command);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MsgCommand_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::auto_control::MsgCommand_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::auto_control::MsgCommand_<ContainerAllocator>& v)
  {
    s << indent << "command: ";
    Printer<float>::stream(s, indent + "  ", v.command);
  }
};

} // namespace message_operations
} // namespace ros

#endif // AUTO_CONTROL_MESSAGE_MSGCOMMAND_H
