control_parameters: {
  pid_parameters: {Kd: 0.0, Ki: 0.02, Kp: 0.05},
  power: {max: 6.4, min: 4},
  step: {power: 2, trigger: 2},
  manual: {power: 6.2},
  automatic: {width: 115, time: 10, mode: 0}
}
