// Generated by gencpp from file camera_measures/MsgStatus.msg
// DO NOT EDIT!


#ifndef CAMERA_MEASURES_MESSAGE_MSGSTATUS_H
#define CAMERA_MEASURES_MESSAGE_MSGSTATUS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace camera_measures
{
template <class ContainerAllocator>
struct MsgStatus_
{
  typedef MsgStatus_<ContainerAllocator> Type;

  MsgStatus_()
    : running(false)
    , laser_on(false)
    , speed(0.0)
    , power(0.0)  {
    }
  MsgStatus_(const ContainerAllocator& _alloc)
    : running(false)
    , laser_on(false)
    , speed(0.0)
    , power(0.0)  {
  (void)_alloc;
    }



   typedef uint8_t _running_type;
  _running_type running;

   typedef uint8_t _laser_on_type;
  _laser_on_type laser_on;

   typedef float _speed_type;
  _speed_type speed;

   typedef float _power_type;
  _power_type power;





  typedef boost::shared_ptr< ::camera_measures::MsgStatus_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::camera_measures::MsgStatus_<ContainerAllocator> const> ConstPtr;

}; // struct MsgStatus_

typedef ::camera_measures::MsgStatus_<std::allocator<void> > MsgStatus;

typedef boost::shared_ptr< ::camera_measures::MsgStatus > MsgStatusPtr;
typedef boost::shared_ptr< ::camera_measures::MsgStatus const> MsgStatusConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::camera_measures::MsgStatus_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::camera_measures::MsgStatus_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace camera_measures

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'camera_measures': ['/home/david/Simtech_ws/src/LaserControl/camera_measures/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::camera_measures::MsgStatus_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::camera_measures::MsgStatus_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::camera_measures::MsgStatus_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::camera_measures::MsgStatus_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::camera_measures::MsgStatus_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::camera_measures::MsgStatus_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::camera_measures::MsgStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9a60217041610aa06a277c2abf60970c";
  }

  static const char* value(const ::camera_measures::MsgStatus_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9a60217041610aa0ULL;
  static const uint64_t static_value2 = 0x6a277c2abf60970cULL;
};

template<class ContainerAllocator>
struct DataType< ::camera_measures::MsgStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "camera_measures/MsgStatus";
  }

  static const char* value(const ::camera_measures::MsgStatus_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::camera_measures::MsgStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool running\n\
bool laser_on\n\
float32 speed\n\
float32 power\n\
";
  }

  static const char* value(const ::camera_measures::MsgStatus_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::camera_measures::MsgStatus_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.running);
      stream.next(m.laser_on);
      stream.next(m.speed);
      stream.next(m.power);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MsgStatus_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::camera_measures::MsgStatus_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::camera_measures::MsgStatus_<ContainerAllocator>& v)
  {
    s << indent << "running: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.running);
    s << indent << "laser_on: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.laser_on);
    s << indent << "speed: ";
    Printer<float>::stream(s, indent + "  ", v.speed);
    s << indent << "power: ";
    Printer<float>::stream(s, indent + "  ", v.power);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CAMERA_MEASURES_MESSAGE_MSGSTATUS_H
