# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from opencv_apps/MaxContourArea.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import std_msgs.msg

class MaxContourArea(genpy.Message):
  _md5sum = "c924e5f1e96fc91c0132097ca211cda0"
  _type = "opencv_apps/MaxContourArea"
  _has_header = True  # flag to mark the presence of a Header object
  _full_text = """Header header
float64 meltpool_contour_area
float64 ellipse_angle
float64 ellipse_x
float64 ellipse_y
float64 ellipse_width
float64 ellipse_height
float64 rectangle_angle
float64 rectangle_x
float64 rectangle_y
float64 rectangle_width
float64 rectangle_height
================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
string frame_id
"""
  __slots__ = ['header','meltpool_contour_area','ellipse_angle','ellipse_x','ellipse_y','ellipse_width','ellipse_height','rectangle_angle','rectangle_x','rectangle_y','rectangle_width','rectangle_height']
  _slot_types = ['std_msgs/Header','float64','float64','float64','float64','float64','float64','float64','float64','float64','float64','float64']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       header,meltpool_contour_area,ellipse_angle,ellipse_x,ellipse_y,ellipse_width,ellipse_height,rectangle_angle,rectangle_x,rectangle_y,rectangle_width,rectangle_height

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(MaxContourArea, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.meltpool_contour_area is None:
        self.meltpool_contour_area = 0.
      if self.ellipse_angle is None:
        self.ellipse_angle = 0.
      if self.ellipse_x is None:
        self.ellipse_x = 0.
      if self.ellipse_y is None:
        self.ellipse_y = 0.
      if self.ellipse_width is None:
        self.ellipse_width = 0.
      if self.ellipse_height is None:
        self.ellipse_height = 0.
      if self.rectangle_angle is None:
        self.rectangle_angle = 0.
      if self.rectangle_x is None:
        self.rectangle_x = 0.
      if self.rectangle_y is None:
        self.rectangle_y = 0.
      if self.rectangle_width is None:
        self.rectangle_width = 0.
      if self.rectangle_height is None:
        self.rectangle_height = 0.
    else:
      self.header = std_msgs.msg.Header()
      self.meltpool_contour_area = 0.
      self.ellipse_angle = 0.
      self.ellipse_x = 0.
      self.ellipse_y = 0.
      self.ellipse_width = 0.
      self.ellipse_height = 0.
      self.rectangle_angle = 0.
      self.rectangle_x = 0.
      self.rectangle_y = 0.
      self.rectangle_width = 0.
      self.rectangle_height = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_11d().pack(_x.meltpool_contour_area, _x.ellipse_angle, _x.ellipse_x, _x.ellipse_y, _x.ellipse_width, _x.ellipse_height, _x.rectangle_angle, _x.rectangle_x, _x.rectangle_y, _x.rectangle_width, _x.rectangle_height))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 88
      (_x.meltpool_contour_area, _x.ellipse_angle, _x.ellipse_x, _x.ellipse_y, _x.ellipse_width, _x.ellipse_height, _x.rectangle_angle, _x.rectangle_x, _x.rectangle_y, _x.rectangle_width, _x.rectangle_height,) = _get_struct_11d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_11d().pack(_x.meltpool_contour_area, _x.ellipse_angle, _x.ellipse_x, _x.ellipse_y, _x.ellipse_width, _x.ellipse_height, _x.rectangle_angle, _x.rectangle_x, _x.rectangle_y, _x.rectangle_width, _x.rectangle_height))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 88
      (_x.meltpool_contour_area, _x.ellipse_angle, _x.ellipse_x, _x.ellipse_y, _x.ellipse_width, _x.ellipse_height, _x.rectangle_angle, _x.rectangle_x, _x.rectangle_y, _x.rectangle_width, _x.rectangle_height,) = _get_struct_11d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_11d = None
def _get_struct_11d():
    global _struct_11d
    if _struct_11d is None:
        _struct_11d = struct.Struct("<11d")
    return _struct_11d
_struct_3I = None
def _get_struct_3I():
    global _struct_3I
    if _struct_3I is None:
        _struct_3I = struct.Struct("<3I")
    return _struct_3I
