// Generated by gencpp from file acoustic_monitoring_msgs/AudioDataStamped.msg
// DO NOT EDIT!


#ifndef ACOUSTIC_MONITORING_MSGS_MESSAGE_AUDIODATASTAMPED_H
#define ACOUSTIC_MONITORING_MSGS_MESSAGE_AUDIODATASTAMPED_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace acoustic_monitoring_msgs
{
template <class ContainerAllocator>
struct AudioDataStamped_
{
  typedef AudioDataStamped_<ContainerAllocator> Type;

  AudioDataStamped_()
    : header()
    , data()  {
    }
  AudioDataStamped_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , data(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector<uint8_t, typename ContainerAllocator::template rebind<uint8_t>::other >  _data_type;
  _data_type data;





  typedef boost::shared_ptr< ::acoustic_monitoring_msgs::AudioDataStamped_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::acoustic_monitoring_msgs::AudioDataStamped_<ContainerAllocator> const> ConstPtr;

}; // struct AudioDataStamped_

typedef ::acoustic_monitoring_msgs::AudioDataStamped_<std::allocator<void> > AudioDataStamped;

typedef boost::shared_ptr< ::acoustic_monitoring_msgs::AudioDataStamped > AudioDataStampedPtr;
typedef boost::shared_ptr< ::acoustic_monitoring_msgs::AudioDataStamped const> AudioDataStampedConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::acoustic_monitoring_msgs::AudioDataStamped_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::acoustic_monitoring_msgs::AudioDataStamped_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::acoustic_monitoring_msgs::AudioDataStamped_<ContainerAllocator1> & lhs, const ::acoustic_monitoring_msgs::AudioDataStamped_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.data == rhs.data;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::acoustic_monitoring_msgs::AudioDataStamped_<ContainerAllocator1> & lhs, const ::acoustic_monitoring_msgs::AudioDataStamped_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace acoustic_monitoring_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::acoustic_monitoring_msgs::AudioDataStamped_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::acoustic_monitoring_msgs::AudioDataStamped_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::acoustic_monitoring_msgs::AudioDataStamped_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::acoustic_monitoring_msgs::AudioDataStamped_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::acoustic_monitoring_msgs::AudioDataStamped_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::acoustic_monitoring_msgs::AudioDataStamped_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::acoustic_monitoring_msgs::AudioDataStamped_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8903b686ebe5db3477e83c6d0bb149f8";
  }

  static const char* value(const ::acoustic_monitoring_msgs::AudioDataStamped_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8903b686ebe5db34ULL;
  static const uint64_t static_value2 = 0x77e83c6d0bb149f8ULL;
};

template<class ContainerAllocator>
struct DataType< ::acoustic_monitoring_msgs::AudioDataStamped_<ContainerAllocator> >
{
  static const char* value()
  {
    return "acoustic_monitoring_msgs/AudioDataStamped";
  }

  static const char* value(const ::acoustic_monitoring_msgs::AudioDataStamped_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::acoustic_monitoring_msgs::AudioDataStamped_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"uint8[] data\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::acoustic_monitoring_msgs::AudioDataStamped_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::acoustic_monitoring_msgs::AudioDataStamped_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct AudioDataStamped_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::acoustic_monitoring_msgs::AudioDataStamped_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::acoustic_monitoring_msgs::AudioDataStamped_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "data[]" << std::endl;
    for (size_t i = 0; i < v.data.size(); ++i)
    {
      s << indent << "  data[" << i << "]: ";
      Printer<uint8_t>::stream(s, indent + "  ", v.data[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // ACOUSTIC_MONITORING_MSGS_MESSAGE_AUDIODATASTAMPED_H
