// Generated by gencpp from file acoustic_monitoring_msgs/MsgAcousticFeature.msg
// DO NOT EDIT!


#ifndef ACOUSTIC_MONITORING_MSGS_MESSAGE_MSGACOUSTICFEATURE_H
#define ACOUSTIC_MONITORING_MSGS_MESSAGE_MSGACOUSTICFEATURE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace acoustic_monitoring_msgs
{
template <class ContainerAllocator>
struct MsgAcousticFeature_
{
  typedef MsgAcousticFeature_<ContainerAllocator> Type;

  MsgAcousticFeature_()
    : header()
    , rms_energy(0.0)
    , amplitude_envelope(0.0)
    , zero_crossing_rate(0.0)
    , mfccs_mean(0.0)
    , mfccs_variance(0.0)
    , spectral_centroids(0.0)
    , spectral_rolloff(0.0)  {
    }
  MsgAcousticFeature_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , rms_energy(0.0)
    , amplitude_envelope(0.0)
    , zero_crossing_rate(0.0)
    , mfccs_mean(0.0)
    , mfccs_variance(0.0)
    , spectral_centroids(0.0)
    , spectral_rolloff(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef float _rms_energy_type;
  _rms_energy_type rms_energy;

   typedef float _amplitude_envelope_type;
  _amplitude_envelope_type amplitude_envelope;

   typedef float _zero_crossing_rate_type;
  _zero_crossing_rate_type zero_crossing_rate;

   typedef float _mfccs_mean_type;
  _mfccs_mean_type mfccs_mean;

   typedef float _mfccs_variance_type;
  _mfccs_variance_type mfccs_variance;

   typedef float _spectral_centroids_type;
  _spectral_centroids_type spectral_centroids;

   typedef float _spectral_rolloff_type;
  _spectral_rolloff_type spectral_rolloff;





  typedef boost::shared_ptr< ::acoustic_monitoring_msgs::MsgAcousticFeature_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::acoustic_monitoring_msgs::MsgAcousticFeature_<ContainerAllocator> const> ConstPtr;

}; // struct MsgAcousticFeature_

typedef ::acoustic_monitoring_msgs::MsgAcousticFeature_<std::allocator<void> > MsgAcousticFeature;

typedef boost::shared_ptr< ::acoustic_monitoring_msgs::MsgAcousticFeature > MsgAcousticFeaturePtr;
typedef boost::shared_ptr< ::acoustic_monitoring_msgs::MsgAcousticFeature const> MsgAcousticFeatureConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::acoustic_monitoring_msgs::MsgAcousticFeature_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::acoustic_monitoring_msgs::MsgAcousticFeature_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::acoustic_monitoring_msgs::MsgAcousticFeature_<ContainerAllocator1> & lhs, const ::acoustic_monitoring_msgs::MsgAcousticFeature_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.rms_energy == rhs.rms_energy &&
    lhs.amplitude_envelope == rhs.amplitude_envelope &&
    lhs.zero_crossing_rate == rhs.zero_crossing_rate &&
    lhs.mfccs_mean == rhs.mfccs_mean &&
    lhs.mfccs_variance == rhs.mfccs_variance &&
    lhs.spectral_centroids == rhs.spectral_centroids &&
    lhs.spectral_rolloff == rhs.spectral_rolloff;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::acoustic_monitoring_msgs::MsgAcousticFeature_<ContainerAllocator1> & lhs, const ::acoustic_monitoring_msgs::MsgAcousticFeature_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace acoustic_monitoring_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::acoustic_monitoring_msgs::MsgAcousticFeature_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::acoustic_monitoring_msgs::MsgAcousticFeature_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::acoustic_monitoring_msgs::MsgAcousticFeature_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::acoustic_monitoring_msgs::MsgAcousticFeature_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::acoustic_monitoring_msgs::MsgAcousticFeature_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::acoustic_monitoring_msgs::MsgAcousticFeature_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::acoustic_monitoring_msgs::MsgAcousticFeature_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c14a16b80445b9cad4c6f29ce8f94aa6";
  }

  static const char* value(const ::acoustic_monitoring_msgs::MsgAcousticFeature_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc14a16b80445b9caULL;
  static const uint64_t static_value2 = 0xd4c6f29ce8f94aa6ULL;
};

template<class ContainerAllocator>
struct DataType< ::acoustic_monitoring_msgs::MsgAcousticFeature_<ContainerAllocator> >
{
  static const char* value()
  {
    return "acoustic_monitoring_msgs/MsgAcousticFeature";
  }

  static const char* value(const ::acoustic_monitoring_msgs::MsgAcousticFeature_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::acoustic_monitoring_msgs::MsgAcousticFeature_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"# time-domain features\n"
"float32 rms_energy\n"
"float32 amplitude_envelope\n"
"float32 zero_crossing_rate\n"
"# frequency-domain features\n"
"# float32 mfccs\n"
"float32 mfccs_mean\n"
"float32 mfccs_variance\n"
"float32 spectral_centroids\n"
"float32 spectral_rolloff\n"
"\n"
"\n"
"# spectral_centroid computes the \"average\" frequency at each frame, where frequencies are weighted relatively by their energy.\n"
"# spectral_bandwidth similar to centroid, but for variance (or other moments).\n"
"# spectral_rolloff essentially the maximum: finds the frequency f such that almost all of the energy (by default, 85%)\n"
"\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::acoustic_monitoring_msgs::MsgAcousticFeature_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::acoustic_monitoring_msgs::MsgAcousticFeature_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.rms_energy);
      stream.next(m.amplitude_envelope);
      stream.next(m.zero_crossing_rate);
      stream.next(m.mfccs_mean);
      stream.next(m.mfccs_variance);
      stream.next(m.spectral_centroids);
      stream.next(m.spectral_rolloff);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MsgAcousticFeature_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::acoustic_monitoring_msgs::MsgAcousticFeature_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::acoustic_monitoring_msgs::MsgAcousticFeature_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "rms_energy: ";
    Printer<float>::stream(s, indent + "  ", v.rms_energy);
    s << indent << "amplitude_envelope: ";
    Printer<float>::stream(s, indent + "  ", v.amplitude_envelope);
    s << indent << "zero_crossing_rate: ";
    Printer<float>::stream(s, indent + "  ", v.zero_crossing_rate);
    s << indent << "mfccs_mean: ";
    Printer<float>::stream(s, indent + "  ", v.mfccs_mean);
    s << indent << "mfccs_variance: ";
    Printer<float>::stream(s, indent + "  ", v.mfccs_variance);
    s << indent << "spectral_centroids: ";
    Printer<float>::stream(s, indent + "  ", v.spectral_centroids);
    s << indent << "spectral_rolloff: ";
    Printer<float>::stream(s, indent + "  ", v.spectral_rolloff);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ACOUSTIC_MONITORING_MSGS_MESSAGE_MSGACOUSTICFEATURE_H
