#Publish all joint states
joint_state_controllerB:
  type: joint_state_controller/JointStateController
  publish_rate: 50

# Joint trajectory controller
position_trajectory_controllerB:
  type: "position_controllers/JointTrajectoryController"
  joints:
    - joint_b1
    - joint_b2
    - joint_b3
    - joint_b4
    - joint_b5
    - joint_b6

  state_publish_rate: 50 # Defaults to 50
  action_monitor_rate: 20 # Defaults to 20
