// Generated by gencpp from file camera_measures/MsgGeometry.msg
// DO NOT EDIT!


#ifndef CAMERA_MEASURES_MESSAGE_MSGGEOMETRY_H
#define CAMERA_MEASURES_MESSAGE_MSGGEOMETRY_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace camera_measures
{
template <class ContainerAllocator>
struct MsgGeometry_
{
  typedef MsgGeometry_<ContainerAllocator> Type;

  MsgGeometry_()
    : header()
    , major_axis(0.0)
    , minor_axis(0.0)
    , orientation(0.0)
    , x(0.0)
    , y(0.0)  {
    }
  MsgGeometry_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , major_axis(0.0)
    , minor_axis(0.0)
    , orientation(0.0)
    , x(0.0)
    , y(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef float _major_axis_type;
  _major_axis_type major_axis;

   typedef float _minor_axis_type;
  _minor_axis_type minor_axis;

   typedef float _orientation_type;
  _orientation_type orientation;

   typedef float _x_type;
  _x_type x;

   typedef float _y_type;
  _y_type y;





  typedef boost::shared_ptr< ::camera_measures::MsgGeometry_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::camera_measures::MsgGeometry_<ContainerAllocator> const> ConstPtr;

}; // struct MsgGeometry_

typedef ::camera_measures::MsgGeometry_<std::allocator<void> > MsgGeometry;

typedef boost::shared_ptr< ::camera_measures::MsgGeometry > MsgGeometryPtr;
typedef boost::shared_ptr< ::camera_measures::MsgGeometry const> MsgGeometryConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::camera_measures::MsgGeometry_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::camera_measures::MsgGeometry_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace camera_measures

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'camera_measures': ['/home/david/SIMTech_ws/src/LaserControl/camera_measures/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::camera_measures::MsgGeometry_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::camera_measures::MsgGeometry_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::camera_measures::MsgGeometry_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::camera_measures::MsgGeometry_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::camera_measures::MsgGeometry_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::camera_measures::MsgGeometry_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::camera_measures::MsgGeometry_<ContainerAllocator> >
{
  static const char* value()
  {
    return "53b067171589c1f92c32f242adc15c57";
  }

  static const char* value(const ::camera_measures::MsgGeometry_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x53b067171589c1f9ULL;
  static const uint64_t static_value2 = 0x2c32f242adc15c57ULL;
};

template<class ContainerAllocator>
struct DataType< ::camera_measures::MsgGeometry_<ContainerAllocator> >
{
  static const char* value()
  {
    return "camera_measures/MsgGeometry";
  }

  static const char* value(const ::camera_measures::MsgGeometry_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::camera_measures::MsgGeometry_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
float32 major_axis\n\
float32 minor_axis\n\
float32 orientation\n\
float32 x\n\
float32 y\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::camera_measures::MsgGeometry_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::camera_measures::MsgGeometry_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.major_axis);
      stream.next(m.minor_axis);
      stream.next(m.orientation);
      stream.next(m.x);
      stream.next(m.y);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MsgGeometry_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::camera_measures::MsgGeometry_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::camera_measures::MsgGeometry_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "major_axis: ";
    Printer<float>::stream(s, indent + "  ", v.major_axis);
    s << indent << "minor_axis: ";
    Printer<float>::stream(s, indent + "  ", v.minor_axis);
    s << indent << "orientation: ";
    Printer<float>::stream(s, indent + "  ", v.orientation);
    s << indent << "x: ";
    Printer<float>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<float>::stream(s, indent + "  ", v.y);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CAMERA_MEASURES_MESSAGE_MSGGEOMETRY_H
