// Generated by gencpp from file camera_measures/MsgPosition.msg
// DO NOT EDIT!


#ifndef CAMERA_MEASURES_MESSAGE_MSGPOSITION_H
#define CAMERA_MEASURES_MESSAGE_MSGPOSITION_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace camera_measures
{
template <class ContainerAllocator>
struct MsgPosition_
{
  typedef MsgPosition_<ContainerAllocator> Type;

  MsgPosition_()
    : header()
    , x(0.0)
    , y(0.0)
    , z(0.0)  {
    }
  MsgPosition_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , x(0.0)
    , y(0.0)
    , z(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef float _x_type;
  _x_type x;

   typedef float _y_type;
  _y_type y;

   typedef float _z_type;
  _z_type z;





  typedef boost::shared_ptr< ::camera_measures::MsgPosition_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::camera_measures::MsgPosition_<ContainerAllocator> const> ConstPtr;

}; // struct MsgPosition_

typedef ::camera_measures::MsgPosition_<std::allocator<void> > MsgPosition;

typedef boost::shared_ptr< ::camera_measures::MsgPosition > MsgPositionPtr;
typedef boost::shared_ptr< ::camera_measures::MsgPosition const> MsgPositionConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::camera_measures::MsgPosition_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::camera_measures::MsgPosition_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace camera_measures

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'std_msgs': ['C:/Opt/ros/melodic/x64/share/std_msgs/cmake/../msg'], 'camera_measures': ['C:/Users/MI/Desktop/Github/src/LaserControl/camera_measures/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::camera_measures::MsgPosition_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::camera_measures::MsgPosition_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::camera_measures::MsgPosition_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::camera_measures::MsgPosition_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::camera_measures::MsgPosition_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::camera_measures::MsgPosition_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::camera_measures::MsgPosition_<ContainerAllocator> >
{
  static const char* value()
  {
    return "75f40115cb5a29c0ceea66f491a5e1a3";
  }

  static const char* value(const ::camera_measures::MsgPosition_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x75f40115cb5a29c0ULL;
  static const uint64_t static_value2 = 0xceea66f491a5e1a3ULL;
};

template<class ContainerAllocator>
struct DataType< ::camera_measures::MsgPosition_<ContainerAllocator> >
{
  static const char* value()
  {
    return "camera_measures/MsgPosition";
  }

  static const char* value(const ::camera_measures::MsgPosition_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::camera_measures::MsgPosition_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"float32 x\n"
"float32 y\n"
"float32 z\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::camera_measures::MsgPosition_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::camera_measures::MsgPosition_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.z);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MsgPosition_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::camera_measures::MsgPosition_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::camera_measures::MsgPosition_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "x: ";
    Printer<float>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<float>::stream(s, indent + "  ", v.y);
    s << indent << "z: ";
    Printer<float>::stream(s, indent + "  ", v.z);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CAMERA_MEASURES_MESSAGE_MSGPOSITION_H
