// Generated by gencpp from file camera_measures/MsgTwist.msg
// DO NOT EDIT!


#ifndef CAMERA_MEASURES_MESSAGE_MSGTWIST_H
#define CAMERA_MEASURES_MESSAGE_MSGTWIST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace camera_measures
{
template <class ContainerAllocator>
struct MsgTwist_
{
  typedef MsgTwist_<ContainerAllocator> Type;

  MsgTwist_()
    : header()
    , linear_x(0.0)
    , linear_y(0.0)
    , linear_z(0.0)  {
    }
  MsgTwist_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , linear_x(0.0)
    , linear_y(0.0)
    , linear_z(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef float _linear_x_type;
  _linear_x_type linear_x;

   typedef float _linear_y_type;
  _linear_y_type linear_y;

   typedef float _linear_z_type;
  _linear_z_type linear_z;





  typedef boost::shared_ptr< ::camera_measures::MsgTwist_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::camera_measures::MsgTwist_<ContainerAllocator> const> ConstPtr;

}; // struct MsgTwist_

typedef ::camera_measures::MsgTwist_<std::allocator<void> > MsgTwist;

typedef boost::shared_ptr< ::camera_measures::MsgTwist > MsgTwistPtr;
typedef boost::shared_ptr< ::camera_measures::MsgTwist const> MsgTwistConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::camera_measures::MsgTwist_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::camera_measures::MsgTwist_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace camera_measures

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'camera_measures': ['/home/david/SIMTech_ws/src/LaserControl/camera_measures/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::camera_measures::MsgTwist_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::camera_measures::MsgTwist_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::camera_measures::MsgTwist_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::camera_measures::MsgTwist_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::camera_measures::MsgTwist_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::camera_measures::MsgTwist_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::camera_measures::MsgTwist_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cc0f6420b30e73cd33eb8167636e926b";
  }

  static const char* value(const ::camera_measures::MsgTwist_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xcc0f6420b30e73cdULL;
  static const uint64_t static_value2 = 0x33eb8167636e926bULL;
};

template<class ContainerAllocator>
struct DataType< ::camera_measures::MsgTwist_<ContainerAllocator> >
{
  static const char* value()
  {
    return "camera_measures/MsgTwist";
  }

  static const char* value(const ::camera_measures::MsgTwist_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::camera_measures::MsgTwist_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
float32 linear_x\n\
float32 linear_y\n\
float32 linear_z\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::camera_measures::MsgTwist_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::camera_measures::MsgTwist_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.linear_x);
      stream.next(m.linear_y);
      stream.next(m.linear_z);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MsgTwist_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::camera_measures::MsgTwist_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::camera_measures::MsgTwist_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "linear_x: ";
    Printer<float>::stream(s, indent + "  ", v.linear_x);
    s << indent << "linear_y: ";
    Printer<float>::stream(s, indent + "  ", v.linear_y);
    s << indent << "linear_z: ";
    Printer<float>::stream(s, indent + "  ", v.linear_z);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CAMERA_MEASURES_MESSAGE_MSGTWIST_H
