// Generated by gencpp from file camera_measures/MsgVelocityStatus.msg
// DO NOT EDIT!


#ifndef CAMERA_MEASURES_MESSAGE_MSGVELOCITYSTATUS_H
#define CAMERA_MEASURES_MESSAGE_MSGVELOCITYSTATUS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace camera_measures
{
template <class ContainerAllocator>
struct MsgVelocityStatus_
{
  typedef MsgVelocityStatus_<ContainerAllocator> Type;

  MsgVelocityStatus_()
    : running(false)
    , speed(0.0)  {
    }
  MsgVelocityStatus_(const ContainerAllocator& _alloc)
    : running(false)
    , speed(0.0)  {
  (void)_alloc;
    }



   typedef uint8_t _running_type;
  _running_type running;

   typedef float _speed_type;
  _speed_type speed;





  typedef boost::shared_ptr< ::camera_measures::MsgVelocityStatus_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::camera_measures::MsgVelocityStatus_<ContainerAllocator> const> ConstPtr;

}; // struct MsgVelocityStatus_

typedef ::camera_measures::MsgVelocityStatus_<std::allocator<void> > MsgVelocityStatus;

typedef boost::shared_ptr< ::camera_measures::MsgVelocityStatus > MsgVelocityStatusPtr;
typedef boost::shared_ptr< ::camera_measures::MsgVelocityStatus const> MsgVelocityStatusConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::camera_measures::MsgVelocityStatus_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::camera_measures::MsgVelocityStatus_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace camera_measures

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg'], 'camera_measures': ['/home/chenlequn/SIMTech_ws/src/LaserControl/camera_measures/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::camera_measures::MsgVelocityStatus_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::camera_measures::MsgVelocityStatus_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::camera_measures::MsgVelocityStatus_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::camera_measures::MsgVelocityStatus_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::camera_measures::MsgVelocityStatus_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::camera_measures::MsgVelocityStatus_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::camera_measures::MsgVelocityStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f12f52908a2201f7da503aef7f554966";
  }

  static const char* value(const ::camera_measures::MsgVelocityStatus_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf12f52908a2201f7ULL;
  static const uint64_t static_value2 = 0xda503aef7f554966ULL;
};

template<class ContainerAllocator>
struct DataType< ::camera_measures::MsgVelocityStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "camera_measures/MsgVelocityStatus";
  }

  static const char* value(const ::camera_measures::MsgVelocityStatus_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::camera_measures::MsgVelocityStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool running\n"
"float32 speed\n"
;
  }

  static const char* value(const ::camera_measures::MsgVelocityStatus_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::camera_measures::MsgVelocityStatus_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.running);
      stream.next(m.speed);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MsgVelocityStatus_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::camera_measures::MsgVelocityStatus_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::camera_measures::MsgVelocityStatus_<ContainerAllocator>& v)
  {
    s << indent << "running: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.running);
    s << indent << "speed: ";
    Printer<float>::stream(s, indent + "  ", v.speed);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CAMERA_MEASURES_MESSAGE_MSGVELOCITYSTATUS_H
