// Generated by gencpp from file infratec_image_processing/MsgHistogram.msg
// DO NOT EDIT!


#ifndef INFRATEC_IMAGE_PROCESSING_MESSAGE_MSGHISTOGRAM_H
#define INFRATEC_IMAGE_PROCESSING_MESSAGE_MSGHISTOGRAM_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace infratec_image_processing
{
template <class ContainerAllocator>
struct MsgHistogram_
{
  typedef MsgHistogram_<ContainerAllocator> Type;

  MsgHistogram_()
    : header()
    , histogram()  {
    }
  MsgHistogram_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , histogram(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector<uint32_t, typename ContainerAllocator::template rebind<uint32_t>::other >  _histogram_type;
  _histogram_type histogram;





  typedef boost::shared_ptr< ::infratec_image_processing::MsgHistogram_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::infratec_image_processing::MsgHistogram_<ContainerAllocator> const> ConstPtr;

}; // struct MsgHistogram_

typedef ::infratec_image_processing::MsgHistogram_<std::allocator<void> > MsgHistogram;

typedef boost::shared_ptr< ::infratec_image_processing::MsgHistogram > MsgHistogramPtr;
typedef boost::shared_ptr< ::infratec_image_processing::MsgHistogram const> MsgHistogramConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::infratec_image_processing::MsgHistogram_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::infratec_image_processing::MsgHistogram_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::infratec_image_processing::MsgHistogram_<ContainerAllocator1> & lhs, const ::infratec_image_processing::MsgHistogram_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.histogram == rhs.histogram;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::infratec_image_processing::MsgHistogram_<ContainerAllocator1> & lhs, const ::infratec_image_processing::MsgHistogram_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace infratec_image_processing

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::infratec_image_processing::MsgHistogram_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::infratec_image_processing::MsgHistogram_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::infratec_image_processing::MsgHistogram_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::infratec_image_processing::MsgHistogram_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::infratec_image_processing::MsgHistogram_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::infratec_image_processing::MsgHistogram_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::infratec_image_processing::MsgHistogram_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8b804f15fac99f33a0d9c6309bbd6803";
  }

  static const char* value(const ::infratec_image_processing::MsgHistogram_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8b804f15fac99f33ULL;
  static const uint64_t static_value2 = 0xa0d9c6309bbd6803ULL;
};

template<class ContainerAllocator>
struct DataType< ::infratec_image_processing::MsgHistogram_<ContainerAllocator> >
{
  static const char* value()
  {
    return "infratec_image_processing/MsgHistogram";
  }

  static const char* value(const ::infratec_image_processing::MsgHistogram_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::infratec_image_processing::MsgHistogram_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"uint32[] histogram\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::infratec_image_processing::MsgHistogram_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::infratec_image_processing::MsgHistogram_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.histogram);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MsgHistogram_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::infratec_image_processing::MsgHistogram_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::infratec_image_processing::MsgHistogram_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "histogram[]" << std::endl;
    for (size_t i = 0; i < v.histogram.size(); ++i)
    {
      s << indent << "  histogram[" << i << "]: ";
      Printer<uint32_t>::stream(s, indent + "  ", v.histogram[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // INFRATEC_IMAGE_PROCESSING_MESSAGE_MSGHISTOGRAM_H
