// Generated by gencpp from file infratec_image_processing/MsgMeltpoolWidth.msg
// DO NOT EDIT!


#ifndef INFRATEC_IMAGE_PROCESSING_MESSAGE_MSGMELTPOOLWIDTH_H
#define INFRATEC_IMAGE_PROCESSING_MESSAGE_MSGMELTPOOLWIDTH_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace infratec_image_processing
{
template <class ContainerAllocator>
struct MsgMeltpoolWidth_
{
  typedef MsgMeltpoolWidth_<ContainerAllocator> Type;

  MsgMeltpoolWidth_()
    : header()
    , melt_pool_width(0.0)  {
    }
  MsgMeltpoolWidth_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , melt_pool_width(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef float _melt_pool_width_type;
  _melt_pool_width_type melt_pool_width;





  typedef boost::shared_ptr< ::infratec_image_processing::MsgMeltpoolWidth_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::infratec_image_processing::MsgMeltpoolWidth_<ContainerAllocator> const> ConstPtr;

}; // struct MsgMeltpoolWidth_

typedef ::infratec_image_processing::MsgMeltpoolWidth_<std::allocator<void> > MsgMeltpoolWidth;

typedef boost::shared_ptr< ::infratec_image_processing::MsgMeltpoolWidth > MsgMeltpoolWidthPtr;
typedef boost::shared_ptr< ::infratec_image_processing::MsgMeltpoolWidth const> MsgMeltpoolWidthConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::infratec_image_processing::MsgMeltpoolWidth_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::infratec_image_processing::MsgMeltpoolWidth_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::infratec_image_processing::MsgMeltpoolWidth_<ContainerAllocator1> & lhs, const ::infratec_image_processing::MsgMeltpoolWidth_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.melt_pool_width == rhs.melt_pool_width;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::infratec_image_processing::MsgMeltpoolWidth_<ContainerAllocator1> & lhs, const ::infratec_image_processing::MsgMeltpoolWidth_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace infratec_image_processing

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::infratec_image_processing::MsgMeltpoolWidth_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::infratec_image_processing::MsgMeltpoolWidth_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::infratec_image_processing::MsgMeltpoolWidth_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::infratec_image_processing::MsgMeltpoolWidth_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::infratec_image_processing::MsgMeltpoolWidth_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::infratec_image_processing::MsgMeltpoolWidth_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::infratec_image_processing::MsgMeltpoolWidth_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e7e9e312c51dbe288dc9af4b67dff15c";
  }

  static const char* value(const ::infratec_image_processing::MsgMeltpoolWidth_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe7e9e312c51dbe28ULL;
  static const uint64_t static_value2 = 0x8dc9af4b67dff15cULL;
};

template<class ContainerAllocator>
struct DataType< ::infratec_image_processing::MsgMeltpoolWidth_<ContainerAllocator> >
{
  static const char* value()
  {
    return "infratec_image_processing/MsgMeltpoolWidth";
  }

  static const char* value(const ::infratec_image_processing::MsgMeltpoolWidth_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::infratec_image_processing::MsgMeltpoolWidth_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"float32 melt_pool_width #pixels\n"
"\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::infratec_image_processing::MsgMeltpoolWidth_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::infratec_image_processing::MsgMeltpoolWidth_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.melt_pool_width);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MsgMeltpoolWidth_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::infratec_image_processing::MsgMeltpoolWidth_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::infratec_image_processing::MsgMeltpoolWidth_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "melt_pool_width: ";
    Printer<float>::stream(s, indent + "  ", v.melt_pool_width);
  }
};

} // namespace message_operations
} // namespace ros

#endif // INFRATEC_IMAGE_PROCESSING_MESSAGE_MSGMELTPOOLWIDTH_H
