// Generated by gencpp from file infratec_image_processing/MsgMeltpool.msg
// DO NOT EDIT!


#ifndef INFRATEC_IMAGE_PROCESSING_MESSAGE_MSGMELTPOOL_H
#define INFRATEC_IMAGE_PROCESSING_MESSAGE_MSGMELTPOOL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace infratec_image_processing
{
template <class ContainerAllocator>
struct MsgMeltpool_
{
  typedef MsgMeltpool_<ContainerAllocator> Type;

  MsgMeltpool_()
    : header()
    , melt_pool_size(0.0)
    , heat_affected_zone(0.0)  {
    }
  MsgMeltpool_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , melt_pool_size(0.0)
    , heat_affected_zone(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef float _melt_pool_size_type;
  _melt_pool_size_type melt_pool_size;

   typedef float _heat_affected_zone_type;
  _heat_affected_zone_type heat_affected_zone;





  typedef boost::shared_ptr< ::infratec_image_processing::MsgMeltpool_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::infratec_image_processing::MsgMeltpool_<ContainerAllocator> const> ConstPtr;

}; // struct MsgMeltpool_

typedef ::infratec_image_processing::MsgMeltpool_<std::allocator<void> > MsgMeltpool;

typedef boost::shared_ptr< ::infratec_image_processing::MsgMeltpool > MsgMeltpoolPtr;
typedef boost::shared_ptr< ::infratec_image_processing::MsgMeltpool const> MsgMeltpoolConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::infratec_image_processing::MsgMeltpool_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::infratec_image_processing::MsgMeltpool_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::infratec_image_processing::MsgMeltpool_<ContainerAllocator1> & lhs, const ::infratec_image_processing::MsgMeltpool_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.melt_pool_size == rhs.melt_pool_size &&
    lhs.heat_affected_zone == rhs.heat_affected_zone;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::infratec_image_processing::MsgMeltpool_<ContainerAllocator1> & lhs, const ::infratec_image_processing::MsgMeltpool_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace infratec_image_processing

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::infratec_image_processing::MsgMeltpool_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::infratec_image_processing::MsgMeltpool_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::infratec_image_processing::MsgMeltpool_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::infratec_image_processing::MsgMeltpool_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::infratec_image_processing::MsgMeltpool_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::infratec_image_processing::MsgMeltpool_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::infratec_image_processing::MsgMeltpool_<ContainerAllocator> >
{
  static const char* value()
  {
    return "53ff07d859c81343775714d56bbac875";
  }

  static const char* value(const ::infratec_image_processing::MsgMeltpool_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x53ff07d859c81343ULL;
  static const uint64_t static_value2 = 0x775714d56bbac875ULL;
};

template<class ContainerAllocator>
struct DataType< ::infratec_image_processing::MsgMeltpool_<ContainerAllocator> >
{
  static const char* value()
  {
    return "infratec_image_processing/MsgMeltpool";
  }

  static const char* value(const ::infratec_image_processing::MsgMeltpool_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::infratec_image_processing::MsgMeltpool_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"float32 melt_pool_size\n"
"float32 heat_affected_zone\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::infratec_image_processing::MsgMeltpool_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::infratec_image_processing::MsgMeltpool_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.melt_pool_size);
      stream.next(m.heat_affected_zone);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MsgMeltpool_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::infratec_image_processing::MsgMeltpool_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::infratec_image_processing::MsgMeltpool_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "melt_pool_size: ";
    Printer<float>::stream(s, indent + "  ", v.melt_pool_size);
    s << indent << "heat_affected_zone: ";
    Printer<float>::stream(s, indent + "  ", v.heat_affected_zone);
  }
};

} // namespace message_operations
} // namespace ros

#endif // INFRATEC_IMAGE_PROCESSING_MESSAGE_MSGMELTPOOL_H
