// Generated by gencpp from file infratec_image_processing/MsgThreshold.msg
// DO NOT EDIT!


#ifndef INFRATEC_IMAGE_PROCESSING_MESSAGE_MSGTHRESHOLD_H
#define INFRATEC_IMAGE_PROCESSING_MESSAGE_MSGTHRESHOLD_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace infratec_image_processing
{
template <class ContainerAllocator>
struct MsgThreshold_
{
  typedef MsgThreshold_<ContainerAllocator> Type;

  MsgThreshold_()
    : header()
    , threshold(0.0)  {
    }
  MsgThreshold_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , threshold(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef float _threshold_type;
  _threshold_type threshold;





  typedef boost::shared_ptr< ::infratec_image_processing::MsgThreshold_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::infratec_image_processing::MsgThreshold_<ContainerAllocator> const> ConstPtr;

}; // struct MsgThreshold_

typedef ::infratec_image_processing::MsgThreshold_<std::allocator<void> > MsgThreshold;

typedef boost::shared_ptr< ::infratec_image_processing::MsgThreshold > MsgThresholdPtr;
typedef boost::shared_ptr< ::infratec_image_processing::MsgThreshold const> MsgThresholdConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::infratec_image_processing::MsgThreshold_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::infratec_image_processing::MsgThreshold_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::infratec_image_processing::MsgThreshold_<ContainerAllocator1> & lhs, const ::infratec_image_processing::MsgThreshold_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.threshold == rhs.threshold;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::infratec_image_processing::MsgThreshold_<ContainerAllocator1> & lhs, const ::infratec_image_processing::MsgThreshold_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace infratec_image_processing

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::infratec_image_processing::MsgThreshold_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::infratec_image_processing::MsgThreshold_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::infratec_image_processing::MsgThreshold_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::infratec_image_processing::MsgThreshold_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::infratec_image_processing::MsgThreshold_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::infratec_image_processing::MsgThreshold_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::infratec_image_processing::MsgThreshold_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3dc898e59e7081935abe13d2f48debb8";
  }

  static const char* value(const ::infratec_image_processing::MsgThreshold_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3dc898e59e708193ULL;
  static const uint64_t static_value2 = 0x5abe13d2f48debb8ULL;
};

template<class ContainerAllocator>
struct DataType< ::infratec_image_processing::MsgThreshold_<ContainerAllocator> >
{
  static const char* value()
  {
    return "infratec_image_processing/MsgThreshold";
  }

  static const char* value(const ::infratec_image_processing::MsgThreshold_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::infratec_image_processing::MsgThreshold_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"float32 threshold #Kelvin\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::infratec_image_processing::MsgThreshold_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::infratec_image_processing::MsgThreshold_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.threshold);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MsgThreshold_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::infratec_image_processing::MsgThreshold_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::infratec_image_processing::MsgThreshold_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "threshold: ";
    Printer<float>::stream(s, indent + "  ", v.threshold);
  }
};

} // namespace message_operations
} // namespace ros

#endif // INFRATEC_IMAGE_PROCESSING_MESSAGE_MSGTHRESHOLD_H
