# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from point_cloud_analysis/MsgHeightMonitoring.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class MsgHeightMonitoring(genpy.Message):
  _md5sum = "d5dba450528743fdd28379753715b42a"
  _type = "point_cloud_analysis/MsgHeightMonitoring"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """int32 plane_id         # the id for the scanning
float32 height_std
float32 height_mean
float32 heighest_max_min_difference
float32 tilt_angle
"""
  __slots__ = ['plane_id','height_std','height_mean','heighest_max_min_difference','tilt_angle']
  _slot_types = ['int32','float32','float32','float32','float32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       plane_id,height_std,height_mean,heighest_max_min_difference,tilt_angle

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(MsgHeightMonitoring, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.plane_id is None:
        self.plane_id = 0
      if self.height_std is None:
        self.height_std = 0.
      if self.height_mean is None:
        self.height_mean = 0.
      if self.heighest_max_min_difference is None:
        self.heighest_max_min_difference = 0.
      if self.tilt_angle is None:
        self.tilt_angle = 0.
    else:
      self.plane_id = 0
      self.height_std = 0.
      self.height_mean = 0.
      self.heighest_max_min_difference = 0.
      self.tilt_angle = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_i4f().pack(_x.plane_id, _x.height_std, _x.height_mean, _x.heighest_max_min_difference, _x.tilt_angle))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 20
      (_x.plane_id, _x.height_std, _x.height_mean, _x.heighest_max_min_difference, _x.tilt_angle,) = _get_struct_i4f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_i4f().pack(_x.plane_id, _x.height_std, _x.height_mean, _x.heighest_max_min_difference, _x.tilt_angle))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 20
      (_x.plane_id, _x.height_std, _x.height_mean, _x.heighest_max_min_difference, _x.tilt_angle,) = _get_struct_i4f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_i4f = None
def _get_struct_i4f():
    global _struct_i4f
    if _struct_i4f is None:
        _struct_i4f = struct.Struct("<i4f")
    return _struct_i4f
