set(simtech_kuka_eki_interface_tcp_MESSAGE_FILES "")
set(simtech_kuka_eki_interface_tcp_SERVICE_FILES "/home/chenlequn/SIMTech_ws/src/simtech_kuka/ethernet_communication_interface/simtech_kuka_eki_interface_tcp/srv/SrvRobotCommand.srv")
