// Generated by gencpp from file defects_identification/MsgDefects.msg
// DO NOT EDIT!


#ifndef DEFECTS_IDENTIFICATION_MESSAGE_MSGDEFECTS_H
#define DEFECTS_IDENTIFICATION_MESSAGE_MSGDEFECTS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace defects_identification
{
template <class ContainerAllocator>
struct MsgDefects_
{
  typedef MsgDefects_<ContainerAllocator> Type;

  MsgDefects_()
    : header()
    , defectsType(0)  {
    }
  MsgDefects_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , defectsType(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef int32_t _defectsType_type;
  _defectsType_type defectsType;





  typedef boost::shared_ptr< ::defects_identification::MsgDefects_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::defects_identification::MsgDefects_<ContainerAllocator> const> ConstPtr;

}; // struct MsgDefects_

typedef ::defects_identification::MsgDefects_<std::allocator<void> > MsgDefects;

typedef boost::shared_ptr< ::defects_identification::MsgDefects > MsgDefectsPtr;
typedef boost::shared_ptr< ::defects_identification::MsgDefects const> MsgDefectsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::defects_identification::MsgDefects_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::defects_identification::MsgDefects_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::defects_identification::MsgDefects_<ContainerAllocator1> & lhs, const ::defects_identification::MsgDefects_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.defectsType == rhs.defectsType;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::defects_identification::MsgDefects_<ContainerAllocator1> & lhs, const ::defects_identification::MsgDefects_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace defects_identification

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::defects_identification::MsgDefects_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::defects_identification::MsgDefects_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::defects_identification::MsgDefects_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::defects_identification::MsgDefects_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::defects_identification::MsgDefects_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::defects_identification::MsgDefects_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::defects_identification::MsgDefects_<ContainerAllocator> >
{
  static const char* value()
  {
    return "def1db136df73f888f606360f32da1ad";
  }

  static const char* value(const ::defects_identification::MsgDefects_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xdef1db136df73f88ULL;
  static const uint64_t static_value2 = 0x8f606360f32da1adULL;
};

template<class ContainerAllocator>
struct DataType< ::defects_identification::MsgDefects_<ContainerAllocator> >
{
  static const char* value()
  {
    return "defects_identification/MsgDefects";
  }

  static const char* value(const ::defects_identification::MsgDefects_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::defects_identification::MsgDefects_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"int32 defectsType  # 0, 1, 2, 3\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::defects_identification::MsgDefects_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::defects_identification::MsgDefects_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.defectsType);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MsgDefects_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::defects_identification::MsgDefects_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::defects_identification::MsgDefects_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "defectsType: ";
    Printer<int32_t>::stream(s, indent + "  ", v.defectsType);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DEFECTS_IDENTIFICATION_MESSAGE_MSGDEFECTS_H
