controller_list:
  - name: fake_abb_irb4400_controller
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
      - joint_6
  - name: fake_tool_controller
    joints:
      []