// Generated by gencpp from file opencv_apps/ContourArea.msg
// DO NOT EDIT!


#ifndef OPENCV_APPS_MESSAGE_CONTOURAREA_H
#define OPENCV_APPS_MESSAGE_CONTOURAREA_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace opencv_apps
{
template <class ContainerAllocator>
struct ContourArea_
{
  typedef ContourArea_<ContainerAllocator> Type;

  ContourArea_()
    : header()
    , area()  {
    }
  ContourArea_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , area(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _area_type;
  _area_type area;





  typedef boost::shared_ptr< ::opencv_apps::ContourArea_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::opencv_apps::ContourArea_<ContainerAllocator> const> ConstPtr;

}; // struct ContourArea_

typedef ::opencv_apps::ContourArea_<std::allocator<void> > ContourArea;

typedef boost::shared_ptr< ::opencv_apps::ContourArea > ContourAreaPtr;
typedef boost::shared_ptr< ::opencv_apps::ContourArea const> ContourAreaConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::opencv_apps::ContourArea_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::opencv_apps::ContourArea_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::opencv_apps::ContourArea_<ContainerAllocator1> & lhs, const ::opencv_apps::ContourArea_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.area == rhs.area;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::opencv_apps::ContourArea_<ContainerAllocator1> & lhs, const ::opencv_apps::ContourArea_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace opencv_apps

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::opencv_apps::ContourArea_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::opencv_apps::ContourArea_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::opencv_apps::ContourArea_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::opencv_apps::ContourArea_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::opencv_apps::ContourArea_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::opencv_apps::ContourArea_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::opencv_apps::ContourArea_<ContainerAllocator> >
{
  static const char* value()
  {
    return "492a39775739bec790d41ced94d2fdc1";
  }

  static const char* value(const ::opencv_apps::ContourArea_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x492a39775739bec7ULL;
  static const uint64_t static_value2 = 0x90d41ced94d2fdc1ULL;
};

template<class ContainerAllocator>
struct DataType< ::opencv_apps::ContourArea_<ContainerAllocator> >
{
  static const char* value()
  {
    return "opencv_apps/ContourArea";
  }

  static const char* value(const ::opencv_apps::ContourArea_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::opencv_apps::ContourArea_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"float64[] area\n"
"\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::opencv_apps::ContourArea_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::opencv_apps::ContourArea_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.area);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ContourArea_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::opencv_apps::ContourArea_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::opencv_apps::ContourArea_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "area[]" << std::endl;
    for (size_t i = 0; i < v.area.size(); ++i)
    {
      s << indent << "  area[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.area[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // OPENCV_APPS_MESSAGE_CONTOURAREA_H
