// Generated by gencpp from file simtech_kuka_eki_interface_machining/SrvRobotCommand.msg
// DO NOT EDIT!


#ifndef SIMTECH_KUKA_EKI_INTERFACE_MACHINING_MESSAGE_SRVROBOTCOMMAND_H
#define SIMTECH_KUKA_EKI_INTERFACE_MACHINING_MESSAGE_SRVROBOTCOMMAND_H

#include <ros/service_traits.h>


#include <simtech_kuka_eki_interface_machining/SrvRobotCommandRequest.h>
#include <simtech_kuka_eki_interface_machining/SrvRobotCommandResponse.h>


namespace simtech_kuka_eki_interface_machining
{

struct SrvRobotCommand
{

typedef SrvRobotCommandRequest Request;
typedef SrvRobotCommandResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SrvRobotCommand
} // namespace simtech_kuka_eki_interface_machining


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::simtech_kuka_eki_interface_machining::SrvRobotCommand > {
  static const char* value()
  {
    return "22c7c465d64c7e74c6ae22029c7ca150";
  }

  static const char* value(const ::simtech_kuka_eki_interface_machining::SrvRobotCommand&) { return value(); }
};

template<>
struct DataType< ::simtech_kuka_eki_interface_machining::SrvRobotCommand > {
  static const char* value()
  {
    return "simtech_kuka_eki_interface_machining/SrvRobotCommand";
  }

  static const char* value(const ::simtech_kuka_eki_interface_machining::SrvRobotCommand&) { return value(); }
};


// service_traits::MD5Sum< ::simtech_kuka_eki_interface_machining::SrvRobotCommandRequest> should match
// service_traits::MD5Sum< ::simtech_kuka_eki_interface_machining::SrvRobotCommand >
template<>
struct MD5Sum< ::simtech_kuka_eki_interface_machining::SrvRobotCommandRequest>
{
  static const char* value()
  {
    return MD5Sum< ::simtech_kuka_eki_interface_machining::SrvRobotCommand >::value();
  }
  static const char* value(const ::simtech_kuka_eki_interface_machining::SrvRobotCommandRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::simtech_kuka_eki_interface_machining::SrvRobotCommandRequest> should match
// service_traits::DataType< ::simtech_kuka_eki_interface_machining::SrvRobotCommand >
template<>
struct DataType< ::simtech_kuka_eki_interface_machining::SrvRobotCommandRequest>
{
  static const char* value()
  {
    return DataType< ::simtech_kuka_eki_interface_machining::SrvRobotCommand >::value();
  }
  static const char* value(const ::simtech_kuka_eki_interface_machining::SrvRobotCommandRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::simtech_kuka_eki_interface_machining::SrvRobotCommandResponse> should match
// service_traits::MD5Sum< ::simtech_kuka_eki_interface_machining::SrvRobotCommand >
template<>
struct MD5Sum< ::simtech_kuka_eki_interface_machining::SrvRobotCommandResponse>
{
  static const char* value()
  {
    return MD5Sum< ::simtech_kuka_eki_interface_machining::SrvRobotCommand >::value();
  }
  static const char* value(const ::simtech_kuka_eki_interface_machining::SrvRobotCommandResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::simtech_kuka_eki_interface_machining::SrvRobotCommandResponse> should match
// service_traits::DataType< ::simtech_kuka_eki_interface_machining::SrvRobotCommand >
template<>
struct DataType< ::simtech_kuka_eki_interface_machining::SrvRobotCommandResponse>
{
  static const char* value()
  {
    return DataType< ::simtech_kuka_eki_interface_machining::SrvRobotCommand >::value();
  }
  static const char* value(const ::simtech_kuka_eki_interface_machining::SrvRobotCommandResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SIMTECH_KUKA_EKI_INTERFACE_MACHINING_MESSAGE_SRVROBOTCOMMAND_H
