// Generated by gencpp from file laser_control/MsgEmission.msg
// DO NOT EDIT!


#ifndef LASER_CONTROL_MESSAGE_MSGEMISSION_H
#define LASER_CONTROL_MESSAGE_MSGEMISSION_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace laser_control
{
template <class ContainerAllocator>
struct MsgEmission_
{
  typedef MsgEmission_<ContainerAllocator> Type;

  MsgEmission_()
    : emission(false)  {
    }
  MsgEmission_(const ContainerAllocator& _alloc)
    : emission(false)  {
  (void)_alloc;
    }



   typedef uint8_t _emission_type;
  _emission_type emission;





  typedef boost::shared_ptr< ::laser_control::MsgEmission_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::laser_control::MsgEmission_<ContainerAllocator> const> ConstPtr;

}; // struct MsgEmission_

typedef ::laser_control::MsgEmission_<std::allocator<void> > MsgEmission;

typedef boost::shared_ptr< ::laser_control::MsgEmission > MsgEmissionPtr;
typedef boost::shared_ptr< ::laser_control::MsgEmission const> MsgEmissionConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::laser_control::MsgEmission_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::laser_control::MsgEmission_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace laser_control

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg'], 'laser_control': ['/home/chenlequn/SIMTech_ws/src/LaserControl/laser_control/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::laser_control::MsgEmission_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::laser_control::MsgEmission_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::laser_control::MsgEmission_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::laser_control::MsgEmission_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::laser_control::MsgEmission_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::laser_control::MsgEmission_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::laser_control::MsgEmission_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b41438f20140254925ccd78f3541f322";
  }

  static const char* value(const ::laser_control::MsgEmission_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb41438f201402549ULL;
  static const uint64_t static_value2 = 0x25ccd78f3541f322ULL;
};

template<class ContainerAllocator>
struct DataType< ::laser_control::MsgEmission_<ContainerAllocator> >
{
  static const char* value()
  {
    return "laser_control/MsgEmission";
  }

  static const char* value(const ::laser_control::MsgEmission_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::laser_control::MsgEmission_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool emission\n"
;
  }

  static const char* value(const ::laser_control::MsgEmission_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::laser_control::MsgEmission_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.emission);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MsgEmission_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::laser_control::MsgEmission_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::laser_control::MsgEmission_<ContainerAllocator>& v)
  {
    s << indent << "emission: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.emission);
  }
};

} // namespace message_operations
} // namespace ros

#endif // LASER_CONTROL_MESSAGE_MSGEMISSION_H
