// Generated by gencpp from file laser_control/MsgStart.msg
// DO NOT EDIT!


#ifndef LASER_CONTROL_MESSAGE_MSGSTART_H
#define LASER_CONTROL_MESSAGE_MSGSTART_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace laser_control
{
template <class ContainerAllocator>
struct MsgStart_
{
  typedef MsgStart_<ContainerAllocator> Type;

  MsgStart_()
    : control(false)
    , setpoint(0.0)  {
    }
  MsgStart_(const ContainerAllocator& _alloc)
    : control(false)
    , setpoint(0.0)  {
  (void)_alloc;
    }



   typedef uint8_t _control_type;
  _control_type control;

   typedef float _setpoint_type;
  _setpoint_type setpoint;





  typedef boost::shared_ptr< ::laser_control::MsgStart_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::laser_control::MsgStart_<ContainerAllocator> const> ConstPtr;

}; // struct MsgStart_

typedef ::laser_control::MsgStart_<std::allocator<void> > MsgStart;

typedef boost::shared_ptr< ::laser_control::MsgStart > MsgStartPtr;
typedef boost::shared_ptr< ::laser_control::MsgStart const> MsgStartConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::laser_control::MsgStart_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::laser_control::MsgStart_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace laser_control

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg'], 'laser_control': ['/home/chenlequn/SIMTech_ws/src/LaserControl/laser_control/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::laser_control::MsgStart_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::laser_control::MsgStart_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::laser_control::MsgStart_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::laser_control::MsgStart_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::laser_control::MsgStart_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::laser_control::MsgStart_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::laser_control::MsgStart_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e881025c4deef3846ab5aed40f4f106e";
  }

  static const char* value(const ::laser_control::MsgStart_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe881025c4deef384ULL;
  static const uint64_t static_value2 = 0x6ab5aed40f4f106eULL;
};

template<class ContainerAllocator>
struct DataType< ::laser_control::MsgStart_<ContainerAllocator> >
{
  static const char* value()
  {
    return "laser_control/MsgStart";
  }

  static const char* value(const ::laser_control::MsgStart_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::laser_control::MsgStart_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool control\n"
"float32 setpoint\n"
;
  }

  static const char* value(const ::laser_control::MsgStart_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::laser_control::MsgStart_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.control);
      stream.next(m.setpoint);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MsgStart_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::laser_control::MsgStart_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::laser_control::MsgStart_<ContainerAllocator>& v)
  {
    s << indent << "control: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.control);
    s << indent << "setpoint: ";
    Printer<float>::stream(s, indent + "  ", v.setpoint);
  }
};

} // namespace message_operations
} // namespace ros

#endif // LASER_CONTROL_MESSAGE_MSGSTART_H
