(cl:defpackage camera_measures-msg
  (:use )
  (:export
   "<MSGACCELERATION>"
   "MSGACCELERATION"
   "<MSGGEOMETRY>"
   "MSGGEOMETRY"
   "<MSGPOSITION>"
   "MSGPOSITION"
   "<MSGSTATUS>"
   "MSGSTATUS"
   "<MSGTWIST>"
   "MSGTWIST"
   "<MSGVELOCITY>"
   "MSGVELOCITY"
   "<MSGVELOCITYSTATUS>"
   "MSGVELOCITYSTATUS"
  ))

