// Generated by gencpp from file simtech_robot_laser_control/MsgControl.msg
// DO NOT EDIT!


#ifndef SIMTECH_ROBOT_LASER_CONTROL_MESSAGE_MSGCONTROL_H
#define SIMTECH_ROBOT_LASER_CONTROL_MESSAGE_MSGCONTROL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace simtech_robot_laser_control
{
template <class ContainerAllocator>
struct MsgControl_
{
  typedef MsgControl_<ContainerAllocator> Type;

  MsgControl_()
    : change(false)
    , value(0)  {
    }
  MsgControl_(const ContainerAllocator& _alloc)
    : change(false)
    , value(0)  {
  (void)_alloc;
    }



   typedef uint8_t _change_type;
  _change_type change;

   typedef int32_t _value_type;
  _value_type value;





  typedef boost::shared_ptr< ::simtech_robot_laser_control::MsgControl_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::simtech_robot_laser_control::MsgControl_<ContainerAllocator> const> ConstPtr;

}; // struct MsgControl_

typedef ::simtech_robot_laser_control::MsgControl_<std::allocator<void> > MsgControl;

typedef boost::shared_ptr< ::simtech_robot_laser_control::MsgControl > MsgControlPtr;
typedef boost::shared_ptr< ::simtech_robot_laser_control::MsgControl const> MsgControlConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::simtech_robot_laser_control::MsgControl_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::simtech_robot_laser_control::MsgControl_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace simtech_robot_laser_control

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['C:/Opt/ros/melodic/x64/share/std_msgs/cmake/../msg'], 'simtech_robot_laser_control': ['C:/Users/MI/Desktop/Github/src/simtech_abb/simtech_robot_laser_control/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::simtech_robot_laser_control::MsgControl_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::simtech_robot_laser_control::MsgControl_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::simtech_robot_laser_control::MsgControl_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::simtech_robot_laser_control::MsgControl_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::simtech_robot_laser_control::MsgControl_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::simtech_robot_laser_control::MsgControl_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::simtech_robot_laser_control::MsgControl_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c0714776f3b1ecd3928d4fe859ff95f8";
  }

  static const char* value(const ::simtech_robot_laser_control::MsgControl_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc0714776f3b1ecd3ULL;
  static const uint64_t static_value2 = 0x928d4fe859ff95f8ULL;
};

template<class ContainerAllocator>
struct DataType< ::simtech_robot_laser_control::MsgControl_<ContainerAllocator> >
{
  static const char* value()
  {
    return "simtech_robot_laser_control/MsgControl";
  }

  static const char* value(const ::simtech_robot_laser_control::MsgControl_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::simtech_robot_laser_control::MsgControl_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool change\n"
"int32 value\n"
;
  }

  static const char* value(const ::simtech_robot_laser_control::MsgControl_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::simtech_robot_laser_control::MsgControl_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.change);
      stream.next(m.value);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MsgControl_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::simtech_robot_laser_control::MsgControl_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::simtech_robot_laser_control::MsgControl_<ContainerAllocator>& v)
  {
    s << indent << "change: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.change);
    s << indent << "value: ";
    Printer<int32_t>::stream(s, indent + "  ", v.value);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SIMTECH_ROBOT_LASER_CONTROL_MESSAGE_MSGCONTROL_H
