// Generated by gencpp from file simtech_robot_laser_control/MsgInfo.msg
// DO NOT EDIT!


#ifndef SIMTECH_ROBOT_LASER_CONTROL_MESSAGE_MSGINFO_H
#define SIMTECH_ROBOT_LASER_CONTROL_MESSAGE_MSGINFO_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace simtech_robot_laser_control
{
template <class ContainerAllocator>
struct MsgInfo_
{
  typedef MsgInfo_<ContainerAllocator> Type;

  MsgInfo_()
    : header()
    , time()
    , track_number(0)  {
    }
  MsgInfo_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , time(_alloc)
    , track_number(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _time_type;
  _time_type time;

   typedef int32_t _track_number_type;
  _track_number_type track_number;





  typedef boost::shared_ptr< ::simtech_robot_laser_control::MsgInfo_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::simtech_robot_laser_control::MsgInfo_<ContainerAllocator> const> ConstPtr;

}; // struct MsgInfo_

typedef ::simtech_robot_laser_control::MsgInfo_<std::allocator<void> > MsgInfo;

typedef boost::shared_ptr< ::simtech_robot_laser_control::MsgInfo > MsgInfoPtr;
typedef boost::shared_ptr< ::simtech_robot_laser_control::MsgInfo const> MsgInfoConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::simtech_robot_laser_control::MsgInfo_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::simtech_robot_laser_control::MsgInfo_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace simtech_robot_laser_control

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'std_msgs': ['C:/Opt/ros/melodic/x64/share/std_msgs/cmake/../msg'], 'simtech_robot_laser_control': ['C:/Users/MI/Desktop/Github/src/simtech_abb/simtech_robot_laser_control/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::simtech_robot_laser_control::MsgInfo_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::simtech_robot_laser_control::MsgInfo_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::simtech_robot_laser_control::MsgInfo_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::simtech_robot_laser_control::MsgInfo_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::simtech_robot_laser_control::MsgInfo_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::simtech_robot_laser_control::MsgInfo_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::simtech_robot_laser_control::MsgInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e43375f64afc0ea18fe6ceb84397eb65";
  }

  static const char* value(const ::simtech_robot_laser_control::MsgInfo_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe43375f64afc0ea1ULL;
  static const uint64_t static_value2 = 0x8fe6ceb84397eb65ULL;
};

template<class ContainerAllocator>
struct DataType< ::simtech_robot_laser_control::MsgInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "simtech_robot_laser_control/MsgInfo";
  }

  static const char* value(const ::simtech_robot_laser_control::MsgInfo_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::simtech_robot_laser_control::MsgInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"string time\n"
"int32 track_number\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::simtech_robot_laser_control::MsgInfo_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::simtech_robot_laser_control::MsgInfo_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.time);
      stream.next(m.track_number);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MsgInfo_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::simtech_robot_laser_control::MsgInfo_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::simtech_robot_laser_control::MsgInfo_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "time: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.time);
    s << indent << "track_number: ";
    Printer<int32_t>::stream(s, indent + "  ", v.track_number);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SIMTECH_ROBOT_LASER_CONTROL_MESSAGE_MSGINFO_H
