// Generated by gencpp from file Simtech_robot_laser_control/MsgPower.msg
// DO NOT EDIT!


#ifndef SIMTECH_ROBOT_LASER_CONTROL_MESSAGE_MSGPOWER_H
#define SIMTECH_ROBOT_LASER_CONTROL_MESSAGE_MSGPOWER_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace Simtech_robot_laser_control
{
template <class ContainerAllocator>
struct MsgPower_
{
  typedef MsgPower_<ContainerAllocator> Type;

  MsgPower_()
    : header()
    , value(0.0)  {
    }
  MsgPower_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , value(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef float _value_type;
  _value_type value;





  typedef boost::shared_ptr< ::Simtech_robot_laser_control::MsgPower_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::Simtech_robot_laser_control::MsgPower_<ContainerAllocator> const> ConstPtr;

}; // struct MsgPower_

typedef ::Simtech_robot_laser_control::MsgPower_<std::allocator<void> > MsgPower;

typedef boost::shared_ptr< ::Simtech_robot_laser_control::MsgPower > MsgPowerPtr;
typedef boost::shared_ptr< ::Simtech_robot_laser_control::MsgPower const> MsgPowerConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::Simtech_robot_laser_control::MsgPower_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::Simtech_robot_laser_control::MsgPower_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace Simtech_robot_laser_control

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'Simtech_robot_laser_control': ['/home/david/SIMTech_ws/src/simtech_abb/Simtech_robot_laser_control/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::Simtech_robot_laser_control::MsgPower_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::Simtech_robot_laser_control::MsgPower_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::Simtech_robot_laser_control::MsgPower_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::Simtech_robot_laser_control::MsgPower_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::Simtech_robot_laser_control::MsgPower_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::Simtech_robot_laser_control::MsgPower_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::Simtech_robot_laser_control::MsgPower_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4bea522f9243fd34ea7bc74ce85697a8";
  }

  static const char* value(const ::Simtech_robot_laser_control::MsgPower_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4bea522f9243fd34ULL;
  static const uint64_t static_value2 = 0xea7bc74ce85697a8ULL;
};

template<class ContainerAllocator>
struct DataType< ::Simtech_robot_laser_control::MsgPower_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Simtech_robot_laser_control/MsgPower";
  }

  static const char* value(const ::Simtech_robot_laser_control::MsgPower_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::Simtech_robot_laser_control::MsgPower_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
float32 value\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::Simtech_robot_laser_control::MsgPower_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::Simtech_robot_laser_control::MsgPower_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.value);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MsgPower_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::Simtech_robot_laser_control::MsgPower_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::Simtech_robot_laser_control::MsgPower_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "value: ";
    Printer<float>::stream(s, indent + "  ", v.value);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SIMTECH_ROBOT_LASER_CONTROL_MESSAGE_MSGPOWER_H
