// Generated by gencpp from file simtech_robot_laser_control/SrvRobotCommandResponse.msg
// DO NOT EDIT!


#ifndef SIMTECH_ROBOT_LASER_CONTROL_MESSAGE_SRVROBOTCOMMANDRESPONSE_H
#define SIMTECH_ROBOT_LASER_CONTROL_MESSAGE_SRVROBOTCOMMANDRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace simtech_robot_laser_control
{
template <class ContainerAllocator>
struct SrvRobotCommandResponse_
{
  typedef SrvRobotCommandResponse_<ContainerAllocator> Type;

  SrvRobotCommandResponse_()
    : response()  {
    }
  SrvRobotCommandResponse_(const ContainerAllocator& _alloc)
    : response(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _response_type;
  _response_type response;





  typedef boost::shared_ptr< ::simtech_robot_laser_control::SrvRobotCommandResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::simtech_robot_laser_control::SrvRobotCommandResponse_<ContainerAllocator> const> ConstPtr;

}; // struct SrvRobotCommandResponse_

typedef ::simtech_robot_laser_control::SrvRobotCommandResponse_<std::allocator<void> > SrvRobotCommandResponse;

typedef boost::shared_ptr< ::simtech_robot_laser_control::SrvRobotCommandResponse > SrvRobotCommandResponsePtr;
typedef boost::shared_ptr< ::simtech_robot_laser_control::SrvRobotCommandResponse const> SrvRobotCommandResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::simtech_robot_laser_control::SrvRobotCommandResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::simtech_robot_laser_control::SrvRobotCommandResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace simtech_robot_laser_control

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg'], 'simtech_robot_laser_control': ['/home/chenlequn/SIMTech_ws/src/simtech_abb/simtech_robot_laser_control/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::simtech_robot_laser_control::SrvRobotCommandResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::simtech_robot_laser_control::SrvRobotCommandResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::simtech_robot_laser_control::SrvRobotCommandResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::simtech_robot_laser_control::SrvRobotCommandResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::simtech_robot_laser_control::SrvRobotCommandResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::simtech_robot_laser_control::SrvRobotCommandResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::simtech_robot_laser_control::SrvRobotCommandResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6de314e2dc76fbff2b6244a6ad70b68d";
  }

  static const char* value(const ::simtech_robot_laser_control::SrvRobotCommandResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6de314e2dc76fbffULL;
  static const uint64_t static_value2 = 0x2b6244a6ad70b68dULL;
};

template<class ContainerAllocator>
struct DataType< ::simtech_robot_laser_control::SrvRobotCommandResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "simtech_robot_laser_control/SrvRobotCommandResponse";
  }

  static const char* value(const ::simtech_robot_laser_control::SrvRobotCommandResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::simtech_robot_laser_control::SrvRobotCommandResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string response\n"
"\n"
;
  }

  static const char* value(const ::simtech_robot_laser_control::SrvRobotCommandResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::simtech_robot_laser_control::SrvRobotCommandResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.response);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SrvRobotCommandResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::simtech_robot_laser_control::SrvRobotCommandResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::simtech_robot_laser_control::SrvRobotCommandResponse_<ContainerAllocator>& v)
  {
    s << indent << "response: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.response);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SIMTECH_ROBOT_LASER_CONTROL_MESSAGE_SRVROBOTCOMMANDRESPONSE_H
